-- =============================================================================
-- SETUP: Create test environment for access-troubleshooter skill validation
-- =============================================================================

USE ROLE ACCOUNTADMIN;

-- =============================================================================
-- 1. Database, schemas, and tables
-- =============================================================================

CREATE DATABASE IF NOT EXISTS AUTH_TEST_DB;
CREATE SCHEMA IF NOT EXISTS AUTH_TEST_DB.AUTH_TEST_SCHEMA;
CREATE SCHEMA IF NOT EXISTS AUTH_TEST_DB.AUTH_TEST_SCHEMA_2;

CREATE TABLE IF NOT EXISTS AUTH_TEST_DB.AUTH_TEST_SCHEMA.SALES_DATA (
    id INT,
    amount DECIMAL(10,2),
    region VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS AUTH_TEST_DB.AUTH_TEST_SCHEMA.RESTRICTED_DATA (
    id INT,
    secret_value VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS AUTH_TEST_DB.AUTH_TEST_SCHEMA_2.ANALYTICS_DATA (
    id INT,
    metric VARCHAR(50),
    value DECIMAL(10,2)
);

-- View referencing two tables (for EXPLAIN_PRIVILEGES view-body-expansion test)
CREATE OR REPLACE VIEW AUTH_TEST_DB.AUTH_TEST_SCHEMA.EP_TEST_VIEW AS
    SELECT s.id, s.amount, r.secret_value
    FROM AUTH_TEST_DB.AUTH_TEST_SCHEMA.SALES_DATA s
    JOIN AUTH_TEST_DB.AUTH_TEST_SCHEMA.RESTRICTED_DATA r ON s.id = r.id;

-- Inner UDF referenced by the owner's-rights outer UDF
CREATE OR REPLACE FUNCTION AUTH_TEST_DB.AUTH_TEST_SCHEMA.EP_INNER_UDF()
    RETURNS VARCHAR
    LANGUAGE SQL
    AS 'SELECT secret_value FROM AUTH_TEST_DB.AUTH_TEST_SCHEMA.RESTRICTED_DATA LIMIT 1';

-- Owner's-rights UDF: body should NOT be expanded by EXPLAIN_PRIVILEGES
-- (SQL UDFs are owner's-rights by default; EXECUTE AS OWNER is procedure-only syntax)
CREATE OR REPLACE FUNCTION AUTH_TEST_DB.AUTH_TEST_SCHEMA.EP_OUTER_UDF()
    RETURNS VARCHAR
    LANGUAGE SQL
    AS 'SELECT AUTH_TEST_DB.AUTH_TEST_SCHEMA.EP_INNER_UDF()';

-- Masking policy for policy-privilege tests (requires Enterprise edition).
-- Skip on Standard edition — the EP masking-policy eval will be skipped too.
-- To enable: uncomment both statements below on an Enterprise-edition account.
--
-- CREATE MASKING POLICY IF NOT EXISTS AUTH_TEST_DB.AUTH_TEST_SCHEMA.EP_TEST_MASK
--     AS (val VARCHAR) RETURNS VARCHAR ->
--     CASE WHEN CURRENT_ROLE() IN ('TEST_ADMIN_ROLE') THEN val ELSE '***' END;
--
-- ALTER TABLE AUTH_TEST_DB.AUTH_TEST_SCHEMA.SALES_DATA
--     MODIFY COLUMN region SET MASKING POLICY AUTH_TEST_DB.AUTH_TEST_SCHEMA.EP_TEST_MASK;

-- =============================================================================
-- 2. End User roles (AUTH_TEST_USER persona)
-- =============================================================================

-- Role with NO privileges (for testing missing access / security boundary)
CREATE ROLE IF NOT EXISTS TEST_NO_ACCESS_ROLE;

-- Role with only DATABASE usage
CREATE ROLE IF NOT EXISTS TEST_DB_ONLY_ROLE;
GRANT USAGE ON DATABASE AUTH_TEST_DB TO ROLE TEST_DB_ONLY_ROLE;

-- Role with DATABASE + SCHEMA usage (but no table access)
CREATE ROLE IF NOT EXISTS TEST_SCHEMA_ONLY_ROLE;
GRANT USAGE ON DATABASE AUTH_TEST_DB TO ROLE TEST_SCHEMA_ONLY_ROLE;
GRANT USAGE ON SCHEMA AUTH_TEST_DB.AUTH_TEST_SCHEMA TO ROLE TEST_SCHEMA_ONLY_ROLE;

-- Role with SELECT on SALES_DATA only (schema 1)
CREATE ROLE IF NOT EXISTS TEST_SALES_READER_ROLE;
GRANT USAGE ON DATABASE AUTH_TEST_DB TO ROLE TEST_SALES_READER_ROLE;
GRANT USAGE ON SCHEMA AUTH_TEST_DB.AUTH_TEST_SCHEMA TO ROLE TEST_SALES_READER_ROLE;
GRANT SELECT ON TABLE AUTH_TEST_DB.AUTH_TEST_SCHEMA.SALES_DATA TO ROLE TEST_SALES_READER_ROLE;

-- Role with SELECT on RESTRICTED_DATA only (not granted to end user)
CREATE ROLE IF NOT EXISTS TEST_RESTRICTED_READER_ROLE;
GRANT USAGE ON DATABASE AUTH_TEST_DB TO ROLE TEST_RESTRICTED_READER_ROLE;
GRANT USAGE ON SCHEMA AUTH_TEST_DB.AUTH_TEST_SCHEMA TO ROLE TEST_RESTRICTED_READER_ROLE;
GRANT SELECT ON TABLE AUTH_TEST_DB.AUTH_TEST_SCHEMA.RESTRICTED_DATA TO ROLE TEST_RESTRICTED_READER_ROLE;

-- Role with full DML access (SELECT, INSERT, UPDATE, DELETE) on schema 1
CREATE ROLE IF NOT EXISTS TEST_FULL_ACCESS_ROLE;
GRANT USAGE ON DATABASE AUTH_TEST_DB TO ROLE TEST_FULL_ACCESS_ROLE;
GRANT USAGE ON SCHEMA AUTH_TEST_DB.AUTH_TEST_SCHEMA TO ROLE TEST_FULL_ACCESS_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA AUTH_TEST_DB.AUTH_TEST_SCHEMA TO ROLE TEST_FULL_ACCESS_ROLE;

-- Role with CREATE TABLE privilege on schema 1 (not granted to end user by default)
CREATE ROLE IF NOT EXISTS TEST_CREATOR_ROLE;
GRANT USAGE ON DATABASE AUTH_TEST_DB TO ROLE TEST_CREATOR_ROLE;
GRANT USAGE ON SCHEMA AUTH_TEST_DB.AUTH_TEST_SCHEMA TO ROLE TEST_CREATOR_ROLE;
GRANT CREATE TABLE ON SCHEMA AUTH_TEST_DB.AUTH_TEST_SCHEMA TO ROLE TEST_CREATOR_ROLE;

-- Role with access to schema 2 only (for cross-schema testing)
CREATE ROLE IF NOT EXISTS TEST_SCHEMA2_READER_ROLE;
GRANT USAGE ON DATABASE AUTH_TEST_DB TO ROLE TEST_SCHEMA2_READER_ROLE;
GRANT USAGE ON SCHEMA AUTH_TEST_DB.AUTH_TEST_SCHEMA_2 TO ROLE TEST_SCHEMA2_READER_ROLE;
GRANT SELECT ON TABLE AUTH_TEST_DB.AUTH_TEST_SCHEMA_2.ANALYTICS_DATA TO ROLE TEST_SCHEMA2_READER_ROLE;

-- Role with CREATE SCHEMA privilege (for CREATE SCHEMA test)
CREATE ROLE IF NOT EXISTS TEST_SCHEMA_CREATOR_ROLE;
GRANT USAGE ON DATABASE AUTH_TEST_DB TO ROLE TEST_SCHEMA_CREATOR_ROLE;
GRANT CREATE SCHEMA ON DATABASE AUTH_TEST_DB TO ROLE TEST_SCHEMA_CREATOR_ROLE;

-- Partial EP role: USAGE on DB + SCHEMA but no MONITOR (for missing_only partial test)
CREATE ROLE IF NOT EXISTS TEST_PARTIAL_EP_ROLE;
GRANT USAGE ON DATABASE AUTH_TEST_DB TO ROLE TEST_PARTIAL_EP_ROLE;
GRANT USAGE ON SCHEMA AUTH_TEST_DB.AUTH_TEST_SCHEMA TO ROLE TEST_PARTIAL_EP_ROLE;

-- =============================================================================
-- 3. Platform Admin role — Persona 3 (full admin on AUTH_TEST_DB)
-- =============================================================================

CREATE ROLE IF NOT EXISTS TEST_ADMIN_ROLE;
GRANT USAGE ON DATABASE AUTH_TEST_DB TO ROLE TEST_ADMIN_ROLE;
GRANT USAGE ON SCHEMA AUTH_TEST_DB.AUTH_TEST_SCHEMA TO ROLE TEST_ADMIN_ROLE;
GRANT USAGE ON SCHEMA AUTH_TEST_DB.AUTH_TEST_SCHEMA_2 TO ROLE TEST_ADMIN_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA AUTH_TEST_DB.AUTH_TEST_SCHEMA TO ROLE TEST_ADMIN_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA AUTH_TEST_DB.AUTH_TEST_SCHEMA_2 TO ROLE TEST_ADMIN_ROLE;
GRANT MANAGE GRANTS ON ACCOUNT TO ROLE TEST_ADMIN_ROLE;
GRANT CREATE ROLE ON ACCOUNT TO ROLE TEST_ADMIN_ROLE;

-- Sales DB Admin: full control over AUTH_TEST_DB, can grant/create roles
CREATE ROLE IF NOT EXISTS TEST_SALES_DB_ADMIN_ROLE;
GRANT ALL PRIVILEGES ON DATABASE AUTH_TEST_DB TO ROLE TEST_SALES_DB_ADMIN_ROLE;
GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE AUTH_TEST_DB TO ROLE TEST_SALES_DB_ADMIN_ROLE;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA AUTH_TEST_DB.AUTH_TEST_SCHEMA TO ROLE TEST_SALES_DB_ADMIN_ROLE;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA AUTH_TEST_DB.AUTH_TEST_SCHEMA_2 TO ROLE TEST_SALES_DB_ADMIN_ROLE;
GRANT CREATE ROLE ON ACCOUNT TO ROLE TEST_SALES_DB_ADMIN_ROLE;
GRANT MANAGE GRANTS ON ACCOUNT TO ROLE TEST_SALES_DB_ADMIN_ROLE;

-- =============================================================================
-- 4. End User (cannot grant, can only inspect own access)
-- =============================================================================

CREATE USER IF NOT EXISTS AUTH_TEST_USER
    PASSWORD = 'TestPass123!'
    DEFAULT_ROLE = TEST_NO_ACCESS_ROLE;

GRANT ROLE TEST_NO_ACCESS_ROLE TO USER AUTH_TEST_USER;
GRANT ROLE TEST_DB_ONLY_ROLE TO USER AUTH_TEST_USER;
GRANT ROLE TEST_SCHEMA_ONLY_ROLE TO USER AUTH_TEST_USER;
GRANT ROLE TEST_SALES_READER_ROLE TO USER AUTH_TEST_USER;
GRANT ROLE TEST_SCHEMA2_READER_ROLE TO USER AUTH_TEST_USER;
GRANT ROLE TEST_CREATOR_ROLE TO USER AUTH_TEST_USER;
-- NOT granting: TEST_RESTRICTED_READER_ROLE (to test "find existing role" path)
-- NOT granting: TEST_FULL_ACCESS_ROLE (to test "find existing role" path)
-- NOT granting: TEST_SCHEMA_CREATOR_ROLE (to test CREATE SCHEMA path)

-- =============================================================================
-- 5. Admin User — Persona 3 (Platform Admin) and Persona 4 (Account Admin)
-- =============================================================================

CREATE USER IF NOT EXISTS AUTH_TEST_ADMIN
    PASSWORD = 'AdminPass123!'
    DEFAULT_ROLE = TEST_SALES_DB_ADMIN_ROLE;

GRANT ROLE TEST_ADMIN_ROLE TO USER AUTH_TEST_ADMIN;
GRANT ROLE TEST_SALES_DB_ADMIN_ROLE TO USER AUTH_TEST_ADMIN;
GRANT ROLE ACCOUNTADMIN TO USER AUTH_TEST_ADMIN;

-- =============================================================================
-- 6. SUGGEST_ROLE_GRANTS fixture — Sales/Finance RBAC hierarchy
--    Mirrors SuggestRoleGrantsIT.java for full IT-parity coverage.
--    Prefix: SRG_ to avoid collisions with existing AUTH_TEST_ objects.
-- =============================================================================

-- 6a. Databases, schemas, tables -----------------------------------------------

CREATE DATABASE IF NOT EXISTS SRG_SALES_DB;
CREATE SCHEMA IF NOT EXISTS SRG_SALES_DB.ANALYTICS;
CREATE TABLE IF NOT EXISTS SRG_SALES_DB.ANALYTICS.ORDERS (
    id INT,
    amount DECIMAL(10,2),
    region VARCHAR(50)
);

CREATE DATABASE IF NOT EXISTS SRG_FINANCE_DB;
CREATE SCHEMA IF NOT EXISTS SRG_FINANCE_DB.REPORTS;
CREATE TABLE IF NOT EXISTS SRG_FINANCE_DB.REPORTS.BUDGET (
    id INT,
    dept VARCHAR(50),
    total DECIMAL(12,2)
);

-- 6b. Roles (14) ---------------------------------------------------------------

CREATE ROLE IF NOT EXISTS SRG_SALES_IDENTITY;
CREATE ROLE IF NOT EXISTS SRG_SALES_DB_ACCESS;
CREATE ROLE IF NOT EXISTS SRG_SALES_ANALYTICS_ACCESS;
CREATE ROLE IF NOT EXISTS SRG_SALES_READ;
CREATE ROLE IF NOT EXISTS SRG_SALES_WRITE;
CREATE ROLE IF NOT EXISTS SRG_SALES_ADMIN;
CREATE ROLE IF NOT EXISTS SRG_FINANCE_IDENTITY;
CREATE ROLE IF NOT EXISTS SRG_FINANCE_DB_ACCESS;
CREATE ROLE IF NOT EXISTS SRG_FINANCE_REPORTS_ACCESS;
CREATE ROLE IF NOT EXISTS SRG_FINANCE_READ;
CREATE ROLE IF NOT EXISTS SRG_FINANCE_DDL;
CREATE ROLE IF NOT EXISTS SRG_READONLY_IDENTITY;
CREATE ROLE IF NOT EXISTS SRG_PARTIAL_IDENTITY;
CREATE ROLE IF NOT EXISTS SRG_PARTIAL_READ;

-- 6c. Role hierarchy -----------------------------------------------------------
--
-- Sales:  SALES_IDENTITY → SALES_DB_ACCESS → SALES_ANALYTICS_ACCESS
--                                                 ├→ SALES_READ
--                                                 ├→ SALES_WRITE
--                                                 └→ SALES_ADMIN
-- Finance: FINANCE_IDENTITY → FINANCE_DB_ACCESS → FINANCE_REPORTS_ACCESS → FINANCE_READ
-- Cross:   READONLY_IDENTITY → SALES_READ
--          PARTIAL_IDENTITY  → PARTIAL_READ

GRANT ROLE SRG_SALES_DB_ACCESS TO ROLE SRG_SALES_IDENTITY;
GRANT ROLE SRG_SALES_ANALYTICS_ACCESS TO ROLE SRG_SALES_DB_ACCESS;
GRANT ROLE SRG_SALES_READ TO ROLE SRG_SALES_ANALYTICS_ACCESS;
GRANT ROLE SRG_SALES_WRITE TO ROLE SRG_SALES_ANALYTICS_ACCESS;
GRANT ROLE SRG_SALES_ADMIN TO ROLE SRG_SALES_ANALYTICS_ACCESS;

GRANT ROLE SRG_FINANCE_DB_ACCESS TO ROLE SRG_FINANCE_IDENTITY;
GRANT ROLE SRG_FINANCE_REPORTS_ACCESS TO ROLE SRG_FINANCE_DB_ACCESS;
GRANT ROLE SRG_FINANCE_READ TO ROLE SRG_FINANCE_REPORTS_ACCESS;

GRANT ROLE SRG_SALES_READ TO ROLE SRG_READONLY_IDENTITY;
GRANT ROLE SRG_PARTIAL_READ TO ROLE SRG_PARTIAL_IDENTITY;

-- 6d. Privilege grants ----------------------------------------------------------

-- Sales privileges
GRANT USAGE ON DATABASE SRG_SALES_DB TO ROLE SRG_SALES_DB_ACCESS;
GRANT USAGE ON SCHEMA SRG_SALES_DB.ANALYTICS TO ROLE SRG_SALES_ANALYTICS_ACCESS;
GRANT SELECT ON TABLE SRG_SALES_DB.ANALYTICS.ORDERS TO ROLE SRG_SALES_READ;
GRANT INSERT, UPDATE ON TABLE SRG_SALES_DB.ANALYTICS.ORDERS TO ROLE SRG_SALES_WRITE;
GRANT ALL PRIVILEGES ON TABLE SRG_SALES_DB.ANALYTICS.ORDERS TO ROLE SRG_SALES_ADMIN;
-- Leaf roles also get direct DB+schema USAGE so they can function standalone
GRANT USAGE ON DATABASE SRG_SALES_DB TO ROLE SRG_SALES_READ;
GRANT USAGE ON DATABASE SRG_SALES_DB TO ROLE SRG_SALES_WRITE;
GRANT USAGE ON DATABASE SRG_SALES_DB TO ROLE SRG_SALES_ADMIN;
GRANT USAGE ON SCHEMA SRG_SALES_DB.ANALYTICS TO ROLE SRG_SALES_READ;
GRANT USAGE ON SCHEMA SRG_SALES_DB.ANALYTICS TO ROLE SRG_SALES_WRITE;
GRANT USAGE ON SCHEMA SRG_SALES_DB.ANALYTICS TO ROLE SRG_SALES_ADMIN;

-- Finance privileges
GRANT USAGE ON DATABASE SRG_FINANCE_DB TO ROLE SRG_FINANCE_DB_ACCESS;
GRANT USAGE ON SCHEMA SRG_FINANCE_DB.REPORTS TO ROLE SRG_FINANCE_REPORTS_ACCESS;
GRANT SELECT ON TABLE SRG_FINANCE_DB.REPORTS.BUDGET TO ROLE SRG_FINANCE_READ;
GRANT USAGE ON DATABASE SRG_FINANCE_DB TO ROLE SRG_FINANCE_READ;
GRANT USAGE ON SCHEMA SRG_FINANCE_DB.REPORTS TO ROLE SRG_FINANCE_READ;

-- Partial: SELECT on ORDERS only, NO USAGE on DB or schema (IT #5)
GRANT SELECT ON TABLE SRG_SALES_DB.ANALYTICS.ORDERS TO ROLE SRG_PARTIAL_READ;

-- Public gets USAGE on FINANCE_DB (mirrors IT fixture)
GRANT USAGE ON DATABASE SRG_FINANCE_DB TO ROLE PUBLIC;

-- Finance DDL: CREATE TABLE + USAGE on FINANCE_DB.REPORTS
GRANT USAGE ON DATABASE SRG_FINANCE_DB TO ROLE SRG_FINANCE_DDL;
GRANT USAGE ON SCHEMA SRG_FINANCE_DB.REPORTS TO ROLE SRG_FINANCE_DDL;
GRANT CREATE TABLE ON SCHEMA SRG_FINANCE_DB.REPORTS TO ROLE SRG_FINANCE_DDL;

-- 6e. Users (5) ----------------------------------------------------------------
-- U1: Sales (fully authorized for SELECT on ORDERS)
-- U2: Finance (no sales access; has READ on BUDGET, no CREATE TABLE)
-- U3: Readonly (SALES_READ only, via READONLY_IDENTITY)
-- U5: Partial (PARTIAL_READ: SELECT on ORDERS but no USAGE)
-- U6: Finance DDL (can CREATE TABLE in FINANCE_DB.REPORTS)

CREATE USER IF NOT EXISTS SRG_USER_1
    PASSWORD = 'TestPass123!'
    DEFAULT_ROLE = SRG_SALES_IDENTITY;
CREATE USER IF NOT EXISTS SRG_USER_2
    PASSWORD = 'TestPass123!'
    DEFAULT_ROLE = SRG_FINANCE_IDENTITY;
CREATE USER IF NOT EXISTS SRG_USER_3
    PASSWORD = 'TestPass123!'
    DEFAULT_ROLE = SRG_READONLY_IDENTITY;
CREATE USER IF NOT EXISTS SRG_USER_5
    PASSWORD = 'TestPass123!'
    DEFAULT_ROLE = SRG_PARTIAL_IDENTITY;
CREATE USER IF NOT EXISTS SRG_USER_6
    PASSWORD = 'TestPass123!'
    DEFAULT_ROLE = SRG_FINANCE_DDL;

GRANT ROLE SRG_SALES_IDENTITY TO USER SRG_USER_1;
GRANT ROLE SRG_FINANCE_IDENTITY TO USER SRG_USER_2;
GRANT ROLE SRG_READONLY_IDENTITY TO USER SRG_USER_3;
GRANT ROLE SRG_PARTIAL_IDENTITY TO USER SRG_USER_5;
GRANT ROLE SRG_FINANCE_DDL TO USER SRG_USER_6;

-- =============================================================================
-- VERIFICATION: Check setup
-- =============================================================================
SHOW GRANTS TO USER AUTH_TEST_USER;
SHOW GRANTS TO USER AUTH_TEST_ADMIN;
SHOW GRANTS TO ROLE TEST_NO_ACCESS_ROLE;
SHOW GRANTS TO ROLE TEST_SALES_READER_ROLE;
SHOW GRANTS TO ROLE TEST_SCHEMA2_READER_ROLE;
SHOW GRANTS TO ROLE TEST_ADMIN_ROLE;
SHOW GRANTS TO ROLE TEST_SALES_DB_ADMIN_ROLE;
SHOW GRANTS TO ROLE TEST_CREATOR_ROLE;
SHOW GRANTS TO ROLE TEST_PARTIAL_EP_ROLE;

-- SRG fixture verification
SHOW GRANTS TO USER SRG_USER_1;
SHOW GRANTS TO USER SRG_USER_2;
SHOW GRANTS TO USER SRG_USER_3;
SHOW GRANTS TO USER SRG_USER_5;
SHOW GRANTS TO USER SRG_USER_6;
SHOW GRANTS TO ROLE SRG_SALES_READ;
SHOW GRANTS TO ROLE SRG_SALES_DB_ACCESS;
SHOW GRANTS TO ROLE SRG_FINANCE_DDL;
SHOW GRANTS TO ROLE SRG_PARTIAL_READ;
