-- Cleanup SQL
-- Run after testing

USE ROLE ACCOUNTADMIN;

DROP USER IF EXISTS AUTH_TEST_USER;
DROP USER IF EXISTS AUTH_TEST_ADMIN;

DROP ROLE IF EXISTS TEST_NO_ACCESS_ROLE;
DROP ROLE IF EXISTS TEST_DB_ONLY_ROLE;
DROP ROLE IF EXISTS TEST_SCHEMA_ONLY_ROLE;
DROP ROLE IF EXISTS TEST_SALES_READER_ROLE;
DROP ROLE IF EXISTS TEST_RESTRICTED_READER_ROLE;
DROP ROLE IF EXISTS TEST_FULL_ACCESS_ROLE;
DROP ROLE IF EXISTS TEST_CREATOR_ROLE;
DROP ROLE IF EXISTS TEST_SCHEMA2_READER_ROLE;
DROP ROLE IF EXISTS TEST_SCHEMA_CREATOR_ROLE;
DROP ROLE IF EXISTS TEST_PARTIAL_EP_ROLE;
DROP ROLE IF EXISTS TEST_ADMIN_ROLE;
DROP ROLE IF EXISTS TEST_SALES_DB_ADMIN_ROLE;

-- Drop masking policy before dropping the database (Enterprise edition only).
-- Uncomment if the masking policy was created during setup.
-- ALTER TABLE AUTH_TEST_DB.AUTH_TEST_SCHEMA.SALES_DATA
--     MODIFY COLUMN region UNSET MASKING POLICY;
-- DROP MASKING POLICY IF EXISTS AUTH_TEST_DB.AUTH_TEST_SCHEMA.EP_TEST_MASK;

DROP DATABASE IF EXISTS AUTH_TEST_DB;

-- SRG fixture (SUGGEST_ROLE_GRANTS Sales/Finance hierarchy)
DROP USER IF EXISTS SRG_USER_1;
DROP USER IF EXISTS SRG_USER_2;
DROP USER IF EXISTS SRG_USER_3;
DROP USER IF EXISTS SRG_USER_5;
DROP USER IF EXISTS SRG_USER_6;

DROP ROLE IF EXISTS SRG_SALES_IDENTITY;
DROP ROLE IF EXISTS SRG_SALES_DB_ACCESS;
DROP ROLE IF EXISTS SRG_SALES_ANALYTICS_ACCESS;
DROP ROLE IF EXISTS SRG_SALES_READ;
DROP ROLE IF EXISTS SRG_SALES_WRITE;
DROP ROLE IF EXISTS SRG_SALES_ADMIN;
DROP ROLE IF EXISTS SRG_FINANCE_IDENTITY;
DROP ROLE IF EXISTS SRG_FINANCE_DB_ACCESS;
DROP ROLE IF EXISTS SRG_FINANCE_REPORTS_ACCESS;
DROP ROLE IF EXISTS SRG_FINANCE_READ;
DROP ROLE IF EXISTS SRG_FINANCE_DDL;
DROP ROLE IF EXISTS SRG_READONLY_IDENTITY;
DROP ROLE IF EXISTS SRG_PARTIAL_IDENTITY;
DROP ROLE IF EXISTS SRG_PARTIAL_READ;

DROP DATABASE IF EXISTS SRG_SALES_DB;
DROP DATABASE IF EXISTS SRG_FINANCE_DB;
