# Copyright (c) 2026 Snowflake Inc. All rights reserved.
# Licensed under the Snowflake Skills License.
# Refer to the LICENSE file in the root of this repository for full terms.

r"""Upload pre-bundled SEC 10-K filing PDFs to Snowflake for the PDF extraction demo.

The PDFs and ground-truth manifest are pre-generated by the developer build
script (demos/pdf-field-extraction/build_dataset.py) and shipped as a zip
archive at demos/pdf-field-extraction/data.zip.  This script simply:

1. Extracts the zip to a temporary directory
2. Creates an SSE-encrypted stage (DEMO_SEC_FILING_STAGE)
3. Uploads the bundled PDFs
4. Creates stratified train/test tables with deterministic ground truth

No external downloads, no browser dependencies.

Example:
    uv run --project <SKILL_DIR> python <SKILL_DIR>/src/generate_sec_filing_data.py \
        --connection MY_CONN --database TEMP --schema PUBLIC

"""

from __future__ import annotations

import argparse
import json
import logging
import os
import tempfile
import zipfile
from pathlib import Path

import snowflake.connector

logger = logging.getLogger(__name__)

DEFAULT_ZIP_PATH = (
    Path(__file__).resolve().parent.parent
    / "demos"
    / "pdf-field-extraction"
    / "data.zip"
)


def _extract_zip(zip_path: Path, dest_dir: Path) -> Path:
    if not zip_path.exists():
        raise FileNotFoundError(
            f"Dataset zip not found at {zip_path}. "
            "Run demos/pdf-field-extraction/build_dataset.py first to generate the dataset."
        )
    logger.info(f"Extracting {zip_path.name} to {dest_dir}...")
    with zipfile.ZipFile(zip_path, "r") as zf:
        zf.extractall(dest_dir)
    return dest_dir


def _load_manifest(data_dir: Path) -> list[dict]:
    manifest_path = data_dir / "manifest.json"
    if not manifest_path.exists():
        raise FileNotFoundError(
            f"Manifest not found in extracted data at {manifest_path}."
        )
    with open(manifest_path) as f:
        entries = json.load(f)

    valid = []
    for entry in entries:
        pdf_path = data_dir / entry["pdf_name"]
        if pdf_path.exists():
            valid.append({**entry, "pdf_path": str(pdf_path)})
        else:
            logger.warning(f"PDF missing, skipping: {entry['pdf_name']}")

    if not valid:
        raise FileNotFoundError(f"No PDF files found in {data_dir}.")
    return valid


def setup_stage(
    conn: snowflake.connector.SnowflakeConnection,
    database: str,
    schema: str,
) -> str:
    fqn = f"{database}.{schema}"
    stage_fqn = f"{fqn}.DEMO_SEC_FILING_STAGE"
    cur = conn.cursor()
    cur.execute(f"CREATE SCHEMA IF NOT EXISTS {fqn}")
    cur.execute(f"USE SCHEMA {fqn}")
    cur.execute(
        f"CREATE STAGE {stage_fqn} "
        f"ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE') DIRECTORY = (ENABLE = TRUE)"
    )
    logger.info(f"Stage ready: {stage_fqn}")
    return stage_fqn


def upload_pdfs(
    conn: snowflake.connector.SnowflakeConnection,
    stage_fqn: str,
    entries: list[dict],
) -> None:
    cur = conn.cursor()
    for entry in entries:
        cur.execute(
            f"PUT 'file://{entry['pdf_path']}' @{stage_fqn}/ "
            f"AUTO_COMPRESS=FALSE OVERWRITE=TRUE"
        )

    cur.execute(f"ALTER STAGE {stage_fqn} REFRESH")
    logger.info(f"Uploaded {len(entries)} PDFs to {stage_fqn}")


def create_tables(
    conn: snowflake.connector.SnowflakeConnection,
    database: str,
    schema: str,
    entries: list[dict],
    train_pct: int,
) -> None:
    fqn = f"{database}.{schema}"
    cur = conn.cursor()

    cur.execute(
        f"CREATE TABLE {fqn}.DEMO_SEC_FILING_ALL "
        f"(FILE_PATH VARCHAR, EXPECTED_OUTPUT VARCHAR)"
    )

    label_keys = [
        "company_name",
        "report_date",
        "irs_ein",
        "state_of_incorporation",
        "ticker",
        "exchange",
        "phone",
        "business_address",
        "filer_category",
    ]
    for entry in entries:
        expected = json.dumps(
            {k: entry[k] for k in label_keys if k in entry},
            separators=(",", ":"),
        )
        cur.execute(
            f"INSERT INTO {fqn}.DEMO_SEC_FILING_ALL VALUES (%s, %s)",
            (entry["pdf_name"], expected),
        )

    cur.execute(
        f"CREATE TABLE {fqn}.DEMO_SEC_FILING_TRAIN AS "
        f"SELECT FILE_PATH, EXPECTED_OUTPUT FROM ("
        f"  SELECT *, ROW_NUMBER() OVER (ORDER BY RANDOM(42)) AS _RN,"
        f"  COUNT(*) OVER () AS _TOTAL"
        f"  FROM {fqn}.DEMO_SEC_FILING_ALL"
        f") WHERE _RN <= FLOOR(_TOTAL * {train_pct} / 100)"
    )
    cur.execute(
        f"CREATE TABLE {fqn}.DEMO_SEC_FILING_TEST AS "
        f"SELECT FILE_PATH, EXPECTED_OUTPUT FROM ("
        f"  SELECT *, ROW_NUMBER() OVER (ORDER BY RANDOM(42)) AS _RN,"
        f"  COUNT(*) OVER () AS _TOTAL"
        f"  FROM {fqn}.DEMO_SEC_FILING_ALL"
        f") WHERE _RN > FLOOR(_TOTAL * {train_pct} / 100)"
    )
    cur.execute(f"DROP TABLE IF EXISTS {fqn}.DEMO_SEC_FILING_ALL")

    res = cur.execute(f"SELECT COUNT(*) FROM {fqn}.DEMO_SEC_FILING_TRAIN")
    assert res is not None
    _row = res.fetchone()
    assert _row is not None
    train_n = _row[0]

    res = cur.execute(f"SELECT COUNT(*) FROM {fqn}.DEMO_SEC_FILING_TEST")
    assert res is not None
    _row = res.fetchone()
    assert _row is not None
    test_n = _row[0]

    logger.info(f"  Train: {fqn}.DEMO_SEC_FILING_TRAIN ({train_n} rows)")
    logger.info(f"  Test:  {fqn}.DEMO_SEC_FILING_TEST ({test_n} rows)")


def main(
    connection: str,
    database: str,
    schema: str,
    zip_path: str | None = None,
    train_pct: int = 60,
) -> None:
    src_zip = Path(zip_path) if zip_path else DEFAULT_ZIP_PATH

    with tempfile.TemporaryDirectory() as tmp:
        data_path = _extract_zip(src_zip, Path(tmp))
        entries = _load_manifest(data_path)
        logger.info(f"Found {len(entries)} filings with PDFs")

        logger.info(f"Connecting to Snowflake (connection={connection})...")
        conn = snowflake.connector.connect(
            connection_name=os.getenv("SNOWFLAKE_CONNECTION_NAME") or connection
        )

        try:
            stage_fqn = setup_stage(conn, database, schema)
            logger.info("Uploading PDFs to stage...")
            upload_pdfs(conn, stage_fqn, entries)
            logger.info("Creating train/test tables...")
            create_tables(conn, database, schema, entries, train_pct)
            logger.info("Done!")
        finally:
            conn.close()


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Upload pre-bundled SEC 10-K PDFs for the field extraction demo."
    )
    parser.add_argument("--connection", required=True, help="Snowflake connection name")
    parser.add_argument("--database", required=True, help="Target database")
    parser.add_argument("--schema", required=True, help="Target schema")
    parser.add_argument(
        "--zip-path",
        help="Path to data.zip archive (default: auto-detected from skill layout)",
    )
    parser.add_argument(
        "--train-pct",
        type=int,
        default=60,
        help="Training split percentage (default: 60)",
    )
    args = parser.parse_args()

    logging.basicConfig(
        level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s"
    )
    main(
        connection=args.connection,
        database=args.database,
        schema=args.schema,
        zip_path=args.zip_path,
        train_pct=args.train_pct,
    )
