"""
notebook_cells.py — Cell content definitions for the AI Readiness Snowsight notebook.

Each function returns a string (markdown or Python code) that becomes a single notebook cell.
Parameters are injected via placeholders replaced at build time.
"""

from __future__ import annotations

# ---------------------------------------------------------------------------
# Markdown cells
# ---------------------------------------------------------------------------

def md_title() -> str:
    return """\
# ❄️ AI Readiness Score

**Date:** `__RUN_DATE__` &nbsp;|&nbsp; **Account:** `__ACCOUNT_NAME__` &nbsp;|&nbsp; **Sample:** __SAMPLE_LABEL__ &nbsp;|&nbsp; **Warehouse:** `__WAREHOUSE__`

> This notebook measures how AI-ready your Snowflake account is by analyzing **consumption-ready tables**
> and **semantic view** coverage and quality. Results are cached for fast reruns.

> **⚠️ Note:** Scores reflect the data visible to your current role. Roles with broader privileges can see more tables and semantic views, which may produce different results.

---
"""


def md_step1_scanning() -> str:
    return """\
## 🔍 Step 1 — Scanning your account

| Step | What it does |
|------|-------------|
| **CR scoring** | Scans `access_history` + `query_history` to identify consumption-ready tables |
| **SV + VQR** | Extracts verified queries, then scores semantic view quality |

⏳ *This may take several minutes on large accounts…*
"""


def md_cr_header() -> str:
    return """\
### 📦 CR Table Scoring
"""


def md_sv_header() -> str:
    return """\
### 🔬 SV + VQR Scoring
"""


def md_step2_computing() -> str:
    return """\
## 📊 Step 2 — Computing composite scores

Merging CR table scores with semantic view quality signals to produce:

- **Demand Coverage** — % of analytical reads on consumption-ready tables
- **SV Coverage** — % of CR tables with at least one semantic view
- **SV Quality** — average quality across relevant semantic views
- **SV Readiness** — √(Coverage × Quality) × 100
- **AI Readiness** — (Demand Coverage + SV Readiness) / 2
"""


def md_results_header() -> str:
    return """\
## 🎯 Results

---
"""



def md_footer() -> str:
    return """\
---

*Generated by the AI Readiness Score skill &nbsp;·&nbsp; Data source: `snowflake.account_usage` (trailing 7 days)*

**Methodology:** Each table is scored on Activity (35%), Consumption breadth (30%), Speed (20%), and Freshness (15%)
using a Cobb-Douglas blend. Tables scoring ≥ 0.80 are consumption-ready. Semantic view quality uses a 9-point scale
(6 binary signals + VQR saturation + comment depth).
"""


# ---------------------------------------------------------------------------
# Python code cells
# ---------------------------------------------------------------------------

def code_parameters() -> str:
    return '''\
SAMPLE_PCT = __SAMPLE_PCT__
USE_CACHE = __USE_CACHE__
'''


def code_imports_and_session() -> str:
    return '''\
import json
import math
import time
from datetime import datetime, timedelta, timezone
from concurrent.futures import ThreadPoolExecutor, as_completed
from IPython.display import display, Markdown
from tqdm.auto import tqdm

from snowflake.snowpark.context import get_active_session
from snowflake.connector import DictCursor

session = get_active_session()
conn = session.connection

CACHE_STAGE = "@~/ai_readiness_cache"

info = [{k.lower(): v for k, v in r.items()} for r in conn.cursor(DictCursor).execute(
    "SELECT CURRENT_ACCOUNT() AS account_name, CURRENT_ORGANIZATION_NAME() AS org_name, CURRENT_ROLE() AS role"
).fetchall()]
ACCOUNT_NAME = str(info[0].get("account_name", "UNKNOWN"))
ORG_NAME = str(info[0].get("org_name", ""))
ROLE = str(info[0].get("role", ""))

sample_suffix = f"_s{SAMPLE_PCT}" if SAMPLE_PCT else "_full"
sample_label = f"{SAMPLE_PCT}% sample" if SAMPLE_PCT else "Full scan"

print(f"✅ Connected: {ACCOUNT_NAME} | Org: {ORG_NAME} | Role: {ROLE}")
print(f"   Sample mode: {sample_label} | Cache: {'enabled' if USE_CACHE else 'disabled'}")
'''


def code_cache_helpers() -> str:
    return '''\
def _lower(row):
    return {k.lower(): v for k, v in row.items()}

def run_query(c, sql):
    with c.cursor(DictCursor) as cur:
        cur.execute(sql)
        return [_lower(r) for r in cur.fetchall()]

def cache_path(label):
    return f"{CACHE_STAGE}/{label}.parquet"

def cache_exists(c, path):
    try:
        with c.cursor() as cur:
            cur.execute(f"LIST {path}")
            return len(cur.fetchall()) > 0
    except Exception:
        return False

def _ensure_db_context(c):
    """Ensure the session has a database/schema context for temp object creation."""
    try:
        row = c.cursor().execute("SELECT CURRENT_DATABASE(), CURRENT_SCHEMA()").fetchone()
        if row and row[0] and row[1]:
            return True
        if row and row[0] and not row[1]:
            c.cursor().execute("USE SCHEMA PUBLIC")
            return True
    except Exception:
        pass
    try:
        _user = c.cursor().execute("SELECT CURRENT_USER()").fetchone()[0]
        c.cursor().execute(f'USE DATABASE "USER${_user}"')
        c.cursor().execute("USE SCHEMA PUBLIC")
        return True
    except Exception:
        pass
    raise RuntimeError(
        "NO_DATABASE_CONTEXT: No database is set and USER$ database is not available. "
        "Please specify a database and schema to use."
    )

_ensure_db_context(conn)

def write_cache(c, sql, path):
    sql = sql.rstrip().rstrip(";")
    _ensure_db_context(c)
    with c.cursor() as cur:
        cur.execute(f"""COPY INTO {path} FROM ({sql}) FILE_FORMAT = (TYPE = PARQUET) OVERWRITE = TRUE SINGLE = TRUE HEADER = TRUE MAX_FILE_SIZE = 268435456""")

def read_cache(c, path):
    _ensure_db_context(c)
    import traceback
    for attempt in range(2):
        try:
            with c.cursor() as cur:
                cur.execute("CREATE OR REPLACE TEMP FILE FORMAT _ai_readiness_parquet TYPE = PARQUET")
                cur.execute(f"SELECT $1 FROM {path} (FILE_FORMAT => _ai_readiness_parquet)")
                rows = []
                for (v,) in cur.fetchall():
                    obj = json.loads(v) if isinstance(v, str) else (v if isinstance(v, dict) else json.loads(str(v)))
                    rows.append({k.lower(): val for k, val in obj.items()})
                return rows
        except Exception as exc:
            err_msg = str(exc)
            is_transient = any(s in err_msg for s in ["503", "429", "Timeout", "RetryRequest", "Service Unavailable"])
            if attempt == 0 and is_transient:
                print(f"  ⚠️ Cache read hit transient error (retrying in 3s): {type(exc).__name__}: {err_msg[:200]}")
                time.sleep(3)
            else:
                print(f"  ❌ Cache read failed (will re-query from scratch):")
                print(f"     Error type: {type(exc).__name__}")
                print(f"     Message: {err_msg[:300]}")
                traceback.print_exc()
                return []

def write_json_cache(c, data, path):
    escaped = data.replace("\\\\", "\\\\\\\\").replace("'", "''")
    _ensure_db_context(c)
    with c.cursor() as cur:
        cur.execute(f"""COPY INTO {path} FROM (SELECT '{escaped}' AS json_payload) FILE_FORMAT = (TYPE = PARQUET) OVERWRITE = TRUE SINGLE = TRUE HEADER = TRUE MAX_FILE_SIZE = 268435456""")

def read_json_cache(c, path):
    _ensure_db_context(c)
    import traceback
    for attempt in range(2):
        try:
            with c.cursor() as cur:
                cur.execute("CREATE OR REPLACE TEMP FILE FORMAT _ai_readiness_parquet TYPE = PARQUET")
            rows = run_query(c, f"SELECT $1:json_payload::STRING AS json_payload FROM {path} (FILE_FORMAT => _ai_readiness_parquet)")
            return rows[0].get("json_payload") if rows else None
        except Exception as exc:
            err_msg = str(exc)
            is_transient = any(s in err_msg for s in ["503", "429", "Timeout", "RetryRequest", "Service Unavailable"])
            if attempt == 0 and is_transient:
                print(f"  ⚠️ JSON cache read hit transient error (retrying in 3s): {type(exc).__name__}: {err_msg[:200]}")
                time.sleep(3)
            else:
                print(f"  ❌ JSON cache read failed (will re-query from scratch):")
                print(f"     Error type: {type(exc).__name__}")
                print(f"     Message: {err_msg[:300]}")
                traceback.print_exc()
                return None

print("🔧 Cache helpers ready")
'''


def code_sql_cr_tables() -> str:
    return r'''
SQL_CR_TABLES = """
__CR_TABLES_SQL__
"""
print(f"📋 CR tables query loaded ({len(SQL_CR_TABLES.strip()):,} chars)")
'''


def code_sql_sv_quality() -> str:
    return r'''
SQL_SV_QUALITY = """
__SV_QUALITY_SQL__
"""
print(f"📋 SV quality query loaded ({len(SQL_SV_QUALITY.strip()):,} chars)")
'''


def code_scan_variables() -> str:
    return r'''
now = datetime.now(timezone.utc)
start_ts = (now - timedelta(days=7)).strftime('%Y-%m-%d %H:%M:%S')
end_ts = now.strftime('%Y-%m-%d %H:%M:%S')
freshness_start_ts = (now - timedelta(days=60)).strftime('%Y-%m-%d %H:%M:%S')

sample_predicate = f"AND MOD(ABS(HASH(ah.query_id) % 100), 100) < {SAMPLE_PCT}" if SAMPLE_PCT else ""

cr_results = []
sv_results = []
vqr_data = {}
execution_times = {}

print(f"📅 Window: {start_ts} → {end_ts}")
print(f"   Sample predicate: {sample_predicate or '(none — full scan)'}")
'''


def code_cr_scoring() -> str:
    return r'''
def run_cr_step():
    global cr_results
    t0 = time.perf_counter()
    cr_cache_p = cache_path(f"cr_tables{sample_suffix}")
    c = session.connection

    if USE_CACHE and cache_exists(c, cr_cache_p):
        print("  [CR] Reading from cache...")
        cr_results = read_cache(c, cr_cache_p)
    else:
        print("  [CR] Scoring table consumption readiness...")
        cr_sql = SQL_CR_TABLES.format(
            sample_predicate=sample_predicate,
            start_ts=start_ts,
            end_ts=end_ts,
            freshness_start_ts=freshness_start_ts,
        )
        cr_results = run_query(c, cr_sql)
        try:
            write_cache(c, cr_sql, cr_cache_p)
        except Exception as exc:
            print(f"  [CR] Cache write failed (non-fatal): {exc}")

    n_cr = sum(1 for r in cr_results if float(r.get("consumption_readiness_score") or 0) >= 0.80)
    elapsed = time.perf_counter() - t0
    execution_times["cr"] = elapsed
    print(f"  [CR] ✅ Scored {len(cr_results):,} tables, {n_cr:,} consumption-ready [{elapsed:.1f}s]")

run_cr_step()
'''


def code_sv_scoring() -> str:
    return r'''
def describe_view_vqr(c, fqn):
    quoted = fqn["quoted"]
    display = fqn["display"]
    last_err = None
    for attempt in range(3):
        try:
            with c.cursor(DictCursor) as cur:
                cur.execute(f"DESCRIBE SEMANTIC VIEW {quoted}", timeout=20)
                rows = [_lower(r) for r in cur.fetchall()]
            vqr_count = 0
            for row in rows:
                kind = (row.get("object_kind") or "").upper()
                if kind in ("AI_VERIFIED_QUERY", "VERIFIED_QUERY"):
                    vqr_count += 1
                elif kind == "EXTENSION" and (row.get("object_name") or "").upper() == "CA" and (row.get("property") or "").upper() == "VALUE":
                    try:
                        ext = json.loads(row.get("property_value", "{}"))
                        vqr_count += len(ext.get("verified_queries", []))
                        vqr_count += len(ext.get("ai_verified_queries", []))
                    except Exception:
                        pass
            return {"fqn": display, "vqr_count": vqr_count}
        except Exception as e:
            last_err = e
    return {"fqn": display, "vqr_count": None, "error": str(last_err)}


def run_sv_step():
    global sv_results, vqr_data
    t_total = time.perf_counter()
    c = session.connection

    vqr_cache_p = cache_path(f"vqr_counts{sample_suffix}")
    t0 = time.perf_counter()
    if USE_CACHE and cache_exists(c, vqr_cache_p):
        print("  [SV] Reading VQR counts from cache...")
        cached_json = read_json_cache(c, vqr_cache_p)
        vqr_data = json.loads(cached_json) if cached_json else {}
    else:
        if SAMPLE_PCT:
            filter_clause = f"""WHERE sv.deleted IS NULL
            AND EXISTS (
                SELECT 1 FROM SNOWFLAKE.ACCOUNT_USAGE.SEMANTIC_TABLES st
                WHERE st.SEMANTIC_VIEW_ID = sv.SEMANTIC_VIEW_ID
                  AND st.DELETED IS NULL
                  AND (UPPER(st.BASE_TABLE_DATABASE_NAME), UPPER(st.BASE_TABLE_SCHEMA_NAME), UPPER(st.BASE_TABLE_NAME))
                      IN (SELECT DISTINCT
                              UPPER(SPLIT_PART(f.value:objectName::string, '.', 1)),
                              UPPER(SPLIT_PART(f.value:objectName::string, '.', 2)),
                              UPPER(SPLIT_PART(f.value:objectName::string, '.', 3))
                          FROM snowflake.account_usage.access_history ah,
                               LATERAL FLATTEN(input => ah.base_objects_accessed) f
                          WHERE ah.query_start_time::DATE BETWEEN '{start_ts}'::DATE AND '{end_ts}'::DATE
                            AND ARRAY_SIZE(ah.objects_modified) = 0
                            AND f.value:objectDomain::string = 'Table'
                            AND SPLIT_PART(f.value:objectName::string, '.', 2) != ''
                            AND SPLIT_PART(f.value:objectName::string, '.', 3) != ''
                            AND MOD(ABS(HASH(ah.query_id) % 100), 100) < {SAMPLE_PCT})
            )"""
        else:
            filter_clause = "WHERE sv.deleted IS NULL"

        scan_label_vqr = f"{SAMPLE_PCT}% sample filter" if SAMPLE_PCT else "full scan"
        print(f"  [SV] Extracting VQR counts ({scan_label_vqr})...")

        try:
            # Strategy: try SHOW SEMANTIC VIEWS IN ACCOUNT first (one fast call,
            # account-wide). It caps at 10,000 rows. If we hit that ceiling, the
            # result is potentially truncated, so fall back to per-database
            # INFORMATION_SCHEMA.SEMANTIC_VIEWS (10K cap applies per DB).
            #
            # Each row carries both a display FQN (db.schema.name, for logs/
            # results/cache) and a quoted FQN ("db"."schema"."name", safe to
            # embed in DESCRIBE SEMANTIC VIEW even when names contain non-ASCII
            # characters, spaces, lowercase letters, or reserved words).
            SHOW_LIMIT = 10000
            quoted_fqn_expr_show = (
                "'\"' || REPLACE(\"database_name\", '\"', '\"\"') || '\".\"' || "
                "REPLACE(\"schema_name\",   '\"', '\"\"') || '\".\"' || "
                "REPLACE(\"name\",          '\"', '\"\"') || '\"'"
            )
            display_fqn_expr_show = (
                "\"database_name\" || '.' || \"schema_name\" || '.' || \"name\""
            )
            with c.cursor(DictCursor) as cur:
                cur.execute("SHOW SEMANTIC VIEWS IN ACCOUNT")
                cur.execute(
                    f"SELECT {display_fqn_expr_show} AS display_fqn, "
                    f"{quoted_fqn_expr_show} AS quoted_fqn "
                    "FROM TABLE(RESULT_SCAN(LAST_QUERY_ID())) ORDER BY display_fqn"
                )
                show_rows = [_lower(r) for r in cur.fetchall()]

            if len(show_rows) < SHOW_LIMIT:
                seen = set()
                fqns = []
                for row in show_rows:
                    d = row["display_fqn"]
                    if d in seen:
                        continue
                    seen.add(d)
                    fqns.append({"display": d, "quoted": row["quoted_fqn"]})
                print(f"  [SV] Listed {len(fqns):,} semantic views via SHOW")
            else:
                print(
                    f"  [SV] SHOW returned {len(show_rows):,} rows (>= {SHOW_LIMIT:,}); "
                    "result may be truncated — falling back to INFORMATION_SCHEMA per database"
                )
                with c.cursor(DictCursor) as cur:
                    cur.execute("SHOW DATABASES")
                    cur.execute(
                        'SELECT "name" AS db_name FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))'
                    )
                    db_names = [row["db_name"] for row in cur.fetchall()]

                quoted_fqn_expr_info = (
                    "'\"' || REPLACE(\"CATALOG\", '\"', '\"\"') || '\".\"' || "
                    "REPLACE(\"SCHEMA\",  '\"', '\"\"') || '\".\"' || "
                    "REPLACE(\"NAME\",    '\"', '\"\"') || '\"'"
                )
                display_fqn_expr_info = (
                    "\"CATALOG\" || '.' || \"SCHEMA\" || '.' || \"NAME\""
                )
                seen = set()
                fqns = []
                for db in db_names:
                    safe_db = db.replace('"', '""')
                    try:
                        rows = run_query(
                            c,
                            f"SELECT {display_fqn_expr_info} AS display_fqn, "
                            f"{quoted_fqn_expr_info} AS quoted_fqn "
                            f'FROM "{safe_db}".INFORMATION_SCHEMA.SEMANTIC_VIEWS',
                        )
                        if len(rows) >= SHOW_LIMIT:
                            print(
                                f"  [SV] WARNING: {db} returned {len(rows):,} rows "
                                f"(>= {SHOW_LIMIT:,}); INFORMATION_SCHEMA may also be truncated"
                            )
                        for row in rows:
                            d = row["display_fqn"]
                            if d in seen:
                                continue
                            seen.add(d)
                            fqns.append({"display": d, "quoted": row["quoted_fqn"]})
                    except Exception as exc:
                        # Shares / imported DBs / DBs without USAGE often fail here — skip.
                        print(f"  [SV] Skipping {db}: {exc}")

                fqns.sort(key=lambda x: x["display"])
            print(f"  [SV] Found {len(fqns):,} semantic views to scan")

            results = []
            errors = []
            if fqns:
                executor = ThreadPoolExecutor(max_workers=8)
                try:
                    futures = {executor.submit(describe_view_vqr, c, fqn): fqn["display"] for fqn in fqns}
                    for future in tqdm(as_completed(futures), total=len(fqns), desc="  [SV] Describing views"):
                        try:
                            result = future.result()
                            if "error" in result:
                                errors.append({"fqn": result["fqn"], "error": result["error"]})
                            results.append(result)
                        except Exception as e:
                            errors.append({"fqn": futures[future], "error": str(e)})
                except KeyboardInterrupt:
                    print("  [SV] Interrupted — cancelling queued tasks")
                    executor.shutdown(wait=False, cancel_futures=True)
                    raise
                else:
                    executor.shutdown(wait=True)

            vqr_data = {
                "total_views_scanned": len(results),
                "total_vqrs": sum(r["vqr_count"] for r in results if r["vqr_count"] is not None),
                "views_with_vqrs": sum(1 for r in results if r.get("vqr_count") and r["vqr_count"] > 0),
                "errors": len(errors),
                "results": results,
            }
            print(f"  [SV] Scanned {len(results):,} views, {vqr_data['total_vqrs']:,} total VQRs, {len(errors)} errors")

            try:
                write_json_cache(c, json.dumps(vqr_data), vqr_cache_p)
            except Exception as exc:
                print(f"  [SV] VQR cache write failed (non-fatal): {exc}")
        except Exception as exc:
            print(f"  [SV] VQR extraction failed (non-fatal): {exc}")
            vqr_data = {}

    t_vqr = time.perf_counter() - t0
    print(f"  [SV] VQR step [{t_vqr:.1f}s]")

    vqr_map = {}
    for item in vqr_data.get("results", []):
        fqn = item.get("fqn", "")
        count = item.get("vqr_count")
        if fqn and count is not None:
            vqr_map[fqn] = int(count)

    sv_cache_p = cache_path(f"sv_quality{sample_suffix}")
    t0 = time.perf_counter()
    if USE_CACHE and cache_exists(c, sv_cache_p):
        print("  [SV] Reading SV quality from cache...")
        sv_results = read_cache(c, sv_cache_p)
    else:
        print("  [SV] Scoring semantic view quality...")
        if vqr_map:
            vqr_unions = " UNION ALL ".join(
                f"SELECT '{fqn.replace(chr(39), chr(39)+chr(39))}' AS sv_fqn, {count} AS n_verified_queries"
                for fqn, count in vqr_map.items()
            )
            vqr_source = vqr_unions
        else:
            vqr_source = "SELECT NULL AS sv_fqn, NULL AS n_verified_queries WHERE 1=0"
        sv_sql = SQL_SV_QUALITY.format(vqr_source=vqr_source)
        sv_results = run_query(c, sv_sql)
        try:
            write_cache(c, sv_sql, sv_cache_p)
        except Exception as exc:
            print(f"  [SV] Cache write failed (non-fatal): {exc}")

    t_sv = time.perf_counter() - t0
    n_sv = len({str(r.get("sv_fqn") or "") for r in sv_results if r.get("sv_fqn")})
    elapsed = time.perf_counter() - t_total
    execution_times["sv"] = elapsed
    print(f"  [SV] ✅ Found {n_sv:,} semantic views [{elapsed:.1f}s total]")

run_sv_step()
'''


def code_merge_and_score() -> str:
    return r'''
# --- scoring.py (inlined) ---
__SCORING_PY__
# --- end scoring.py ---

scores = compute_composite_scores(cr_results, sv_results)

# Add account metadata
scores["account_name"] = ACCOUNT_NAME
scores["org_name"] = ORG_NAME
scores["role"] = ROLE
scores["run_date"] = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
scores["sample_pct"] = SAMPLE_PCT

scores_cache_p = cache_path(f"scores{sample_suffix}")
try:
    write_json_cache(conn, json.dumps(scores), scores_cache_p)
    print("💾 Scores cached for future runs")
except Exception as exc:
    print(f"⚠️ Scores cache write failed (non-fatal): {exc}")

print(f"✅ Composite scores computed")
'''


def code_display_results() -> str:
    return r'''
gap_labels = {
    "BUILD_CR_TABLES": "Build consumption-ready tables",
    "BUILD_SVS": "Build semantic views",
    "EXPAND_SV_COVERAGE": "Expand semantic view coverage",
    "IMPROVE_SV_QUALITY": "Improve semantic view quality",
    "HEALTHY": "Maintain your current position",
}

def score_emoji(v):
    if v <= 20: return "🔴"
    if v <= 40: return "🟠"
    if v <= 60: return "🟡"
    if v <= 80: return "🟢"
    return "🟣"

def interpret_score(v):
    if v <= 10: return "Early stage"
    if v <= 30: return "Getting started"
    if v <= 55: return "Building momentum"
    if v <= 75: return "Well positioned"
    return "AI-ready"

md = f"""
# {score_emoji(scores['ai_readiness'])} AI Readiness: **{scores['ai_readiness']:.0f}**/100

> **{interpret_score(scores['ai_readiness'])}** — {gap_labels.get(scores['gap'], scores['gap'])}

---

### Score Breakdown

| Metric | Score | Status |
|--------|------:|--------|
| {score_emoji(scores['ai_readiness'])} **AI Readiness** | **{scores['ai_readiness']:.1f}**/100 | Gap: {scores['gap'].replace('_', ' ').title()} |
| {score_emoji(scores['demand_coverage'])} Demand Coverage | {scores['demand_coverage']:.1f}/100 | {'Strong' if scores['demand_coverage'] >= 70 else 'Moderate' if scores['demand_coverage'] >= 50 else 'Low'} |
| {score_emoji(scores['sv_readiness'])} SV Readiness | {scores['sv_readiness']:.1f}/100 | {'Strong' if scores['sv_readiness'] >= 70 else 'Moderate' if scores['sv_readiness'] >= 50 else 'Low'} |
| {score_emoji(scores['sv_coverage'])} SV Coverage | {scores['sv_coverage']:.1f}/100 | {scores['n_sv_covered']}/{scores['n_cr_tables']} CR tables covered |
| {score_emoji(scores['sv_quality'])} SV Quality | {scores['sv_quality']:.1f}/100 | {'Rich metadata' if scores['sv_quality'] >= 70 else 'Some gaps' if scores['sv_quality'] >= 40 else 'Bare-bones'} |
| 📦 CR Tables | **{scores['n_cr_tables']:,}** | of {scores['n_all_scored']:,} total tables scored |

---

### 💡 Recommendation

**Priority: {gap_labels.get(scores['gap'], scores['gap'])}**

"""

if scores["gap"] == "BUILD_CR_TABLES":
    md += "Most analytical reads land on tables that aren't consumption-ready. Focus on increasing CR table coverage in high-traffic schemas.\n\n"
elif scores["gap"] in ("BUILD_SVS", "EXPAND_SV_COVERAGE") and scores.get("top_targets"):
    md += "**Top uncovered CR tables** (by read volume):\n\n"
    for i, t in enumerate(scores["top_targets"][:5], 1):
        md += f"{i}. `{t}`\n"
    md += "\n"

if scores["gap"] == "IMPROVE_SV_QUALITY" and scores.get("missing_dims"):
    md += f"**Common SV gaps:** {', '.join(scores['missing_dims'])}\n\n"

if scores.get("improvement_items"):
    md += "---\n\n### 📋 Improvement Opportunities\n\n"
    md += "| Type | Target | Detail | Action |\n|------|--------|--------|--------|\n"
    for item in scores["improvement_items"][:10]:
        tag = {"UNCOVERED_CR_TABLE": "Needs SV", "SV_QUALITY_GAP": "Quality gap", "SCHEMA_GAP": "Low CR coverage"}.get(item["type"], item["type"])
        md += f"| {tag} | `{item['target']}` | {item['detail']} | {item['recommendation']} |\n"

display(Markdown(md))
'''


def code_generate_html() -> str:
    return r'''
__REPORT_PY__

__RECOMMENDATIONS_PY__

recommendation_text = build_recommendation(
    account_name=scores["account_name"],
    composite=scores["ai_readiness"],
    gap=scores["gap"],
    pct_demand_coverage=scores["pct_demand_raw"],
    n_cr_tables=scores["n_cr_tables"],
    pct_sv_coverage=scores["pct_sv_coverage_raw"],
    n_sv_covered=scores["n_sv_covered"],
    avg_sv_quality=scores["avg_sv_quality_raw"],
    top_targets=scores["top_targets"],
    missing_dims=scores["missing_dims"],
)

html = render_html(
    account_name=scores["account_name"],
    org_name=scores["org_name"],
    role=scores["role"],
    run_date=scores["run_date"],
    ai_readiness=scores["ai_readiness"],
    demand_coverage=scores["demand_coverage"],
    sv_readiness=scores["sv_readiness"],
    sv_coverage=scores["sv_coverage"],
    sv_quality=scores["sv_quality"],
    n_cr_tables=scores["n_cr_tables"],
    gap=scores["gap"],
    recommendation=recommendation_text,
    improvement_items=scores["improvement_items"],
    sample_pct=scores["sample_pct"],
)

out_path = "/tmp/ai_readiness_report.html"
with open(out_path, "w") as f:
    f.write(html)

try:
    conn.cursor().execute(f"PUT 'file://{out_path}' @~/ai_readiness_cache/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE")
    print(f"📄 HTML report uploaded to @~/ai_readiness_cache/ai_readiness_report.html")
    print("   Download via: GET @~/ai_readiness_cache/ai_readiness_report.html file:///tmp/")
except Exception as exc:
    print(f"📄 HTML report saved to {out_path} (stage upload failed: {exc})")

from IPython.display import display, HTML
display(HTML(html))
'''
