"""Tier-B integration tests for ``render_assessment.build_assessment``.

Focus areas (kept independent from ``scripts/assessment/tests/test_assess.py``,
which already covers the legacy single-source path in depth):

* Backward-compat path: no new flags → behaviour is the legacy one.
* New flag path: ``--migration-state-json`` (no explicit source dir) →
  renderer materializes ``phase-0-source`` itself, populates the
  recipe-resolved panel from ``migration_state.json[recipe_edits]``.
* Post-merge panel assignment: the panel is wired in
  ``Assessment.recipe_resolved`` AFTER the IR merge — no per-merge math
  touches it.
* Recipe-data isolation in the merge: cloning a panel into one side of
  the merge must NOT carry recipe rows through ``merge()`` (the merge
  function deliberately omits any concat rule for ``recipe_resolved``).
"""
from __future__ import annotations

import inspect
import json
import shutil
import subprocess
from pathlib import Path

import pytest

from assess_ir import Assessment, RecipeResolvedRow
from render_assessment import _load_recipe_edits, build_assessment

pytestmark = pytest.mark.skipif(
    shutil.which("git") is None,
    reason="git binary required for the materialize round-trip in build_assessment",
)


def _git(*args: str, cwd: Path) -> None:
    proc = subprocess.run(
        ["git", *args], cwd=cwd, capture_output=True, text=True,
    )
    assert proc.returncode == 0, (
        f"git {' '.join(args)} failed in {cwd}: {proc.stderr}"
    )


@pytest.fixture
def synthetic_conversion(tmp_path: Path) -> Path:
    """A complete synthetic <CONVERSION> tree:
      - Output/workload.py with a recipe-inserted block.
      - analysis.json with one finding on a post-recipe line.
      - migration_state.json with one recipe edit.
      - git repo + phase-0-source tag captured BEFORE the recipe insertion.
    """
    conv = tmp_path / "Conversion-SCOS-TIER-B"
    (conv / "Output").mkdir(parents=True)
    (conv / "Reports").mkdir()

    # Original source (committed at phase-0-source).
    original = (
        "import pyspark\n"
        "from pyspark.sql import SparkSession\n"
        "spark = SparkSession.builder.master(\"local\").getOrCreate()\n"
        "df = spark.range(5)\n"
        "rdd = spark.sparkContext.parallelize([1, 2, 3])\n"
        "print(rdd.collect())\n"
    )
    (conv / "Output" / "workload.py").write_text(original, encoding="utf-8")

    # Bootstrap migration_state.json BEFORE the initial commit so the tag
    # captures it too (matches Phase 0 contract).
    (conv / "migration_state.json").write_text(
        json.dumps({"phase": 0, "metadata": {"project": "tier-b-syn"}}),
        encoding="utf-8",
    )

    # git init + tag phase-0-source.
    _git("init", "--quiet", "-b", "main", cwd=conv)
    _git("config", "user.email", "test@example.com", cwd=conv)
    _git("config", "user.name", "Test User", cwd=conv)
    _git("config", "commit.gpgsign", "false", cwd=conv)
    _git("add", ".", cwd=conv)
    _git("commit", "--quiet", "-m", "Initial commit", cwd=conv)
    _git("tag", "phase-0-source", cwd=conv)

    # Simulate Phase 0.5: insert two recipe-comment lines after line 2.
    post = (
        "import pyspark\n"
        "from pyspark.sql import SparkSession\n"
        "# SCOS-WARN: master() drop applied\n"
        "# generated by recipe spark_builder_drop_master_init_session_rewrite\n"
        "spark = SparkSession.builder.getOrCreate()\n"
        "df = spark.range(5)\n"
        "rdd = spark.sparkContext.parallelize([1, 2, 3])\n"
        "print(rdd.collect())\n"
    )
    (conv / "Output" / "workload.py").write_text(post, encoding="utf-8")

    # Now update migration_state.json with recipe_edits AND phase 1 marker.
    state = {
        "phase": 1,
        "metadata": {"project": "tier-b-syn"},
        "recipe_edits": {
            "workload.py": [
                {
                    "recipe_id": "spark_builder_drop_master_init_session_rewrite",
                    "src_line": 3,
                    "output_line_anchor": "spark_builder_drop_master_init_session_rewrite:3:00000000",
                }
            ]
        },
    }
    (conv / "migration_state.json").write_text(json.dumps(state), encoding="utf-8")

    # analysis.json: one finding on POST line 7 (rdd parallelize). After
    # rebasing, this should land on ORIGINAL line 5.
    findings = [
        {
            "file": str(conv / "Output" / "workload.py"),
            "lines": "7",
            "code": "rdd = spark.sparkContext.parallelize([1, 2, 3])",
            "final_risk": 0.8,
            "confidence": "HIGH",
            "language": "python",
            "root_cause": "RDD operations are not supported in Snowpark Connect",
            "explanation": "RDDs require a Spark driver and cluster.",
            "category": "Unsupported API",
            "code_": "ANALYZER-H",
            "kind": "llm_only",
        }
    ]
    (conv / "analysis.json").write_text(json.dumps(findings), encoding="utf-8")
    return conv


# ---------------------------------------------------------------------------
# Backward-compat path: no new flags → identical legacy behaviour
# ---------------------------------------------------------------------------


def test_backward_compat_no_new_flags_yields_empty_panel(synthetic_conversion: Path) -> None:
    """When neither --original-source-dir nor --migration-state-json is
    provided, the renderer behaves exactly as before: workload_dir is
    scanned, no rebasing happens, recipe_resolved is empty."""
    conv = synthetic_conversion
    assessment = build_assessment(
        project="tier-b-syn",
        analysis_json=conv / "analysis.json",
        workload_dir=conv / "Output",
    )
    assert assessment.recipe_resolved == []
    # The finding's line should be the POST-recipe line (7), since rebasing
    # is disabled without the new flags.
    assert assessment.detailed_findings[0].lines == "7"


# ---------------------------------------------------------------------------
# New flag path: --migration-state-json drives everything
# ---------------------------------------------------------------------------


def test_migration_state_only_materializes_and_rebases(synthetic_conversion: Path) -> None:
    """Passing only --migration-state-json: renderer derives workload_dir,
    materializes the phase-0-source tag, rebases findings, and populates
    the recipe_resolved panel."""
    conv = synthetic_conversion
    assessment = build_assessment(
        project="tier-b-syn",
        analysis_json=conv / "analysis.json",
        migration_state_json=conv / "migration_state.json",
    )

    # Panel populated from recipe_edits.
    assert len(assessment.recipe_resolved) == 1
    row = assessment.recipe_resolved[0]
    assert isinstance(row, RecipeResolvedRow)
    assert row.file == "workload.py"
    assert row.line == 3
    assert row.recipe_id == "spark_builder_drop_master_init_session_rewrite"
    assert row.kind == "rewrite"

    # Finding line was rebased from POST line 7 → ORIGINAL line 5.
    assert assessment.detailed_findings[0].lines == "5"


def test_explicit_original_source_dir_overrides_materialize(
    synthetic_conversion: Path, tmp_path: Path
) -> None:
    """When --original-source-dir is explicit, the renderer does NOT
    materialize from git — it scans the provided dir directly."""
    conv = synthetic_conversion
    # Hand-build an alternative original source dir that differs slightly
    # (so we can prove the renderer used IT, not the git tag).
    alt = tmp_path / "alt-orig"
    alt.mkdir()
    (alt / "workload.py").write_text(
        # 4 lines — wildly different from both original and post versions.
        "X = 1\nY = 2\nZ = 3\nW = 4\n",
        encoding="utf-8",
    )

    assessment = build_assessment(
        project="tier-b-syn",
        analysis_json=conv / "analysis.json",
        workload_dir=conv / "Output",
        original_source_dir=alt,
        migration_state_json=conv / "migration_state.json",
    )
    # The panel still comes from migration_state_json[recipe_edits] (panel
    # is independent of the source-dir wiring).
    assert len(assessment.recipe_resolved) == 1
    # The scan reads from alt/, so file_types should reflect it.
    py_rows = [r for r in assessment.file_types if r.extension.lower() in {"python", ".py", "py"}]
    # At least one row referencing the single-file alt workspace.
    assert assessment.workload.files_scanned >= 1


# ---------------------------------------------------------------------------
# Recipe-data isolation in merge()
# ---------------------------------------------------------------------------


def test_merge_does_not_propagate_recipe_resolved() -> None:
    """The Assessment.merge() function must NOT concatenate recipe_resolved
    rows. Recipe data is assigned exclusively by build_assessment AFTER the
    merge. If a developer ever adds a concat rule here, recipe rows would
    leak in via the analyzer / scanner IR side."""
    a = Assessment()
    a.recipe_resolved = [
        RecipeResolvedRow(file="a.py", line=1, recipe_id="x_rewrite", kind="rewrite"),
    ]
    b = Assessment()
    b.recipe_resolved = [
        RecipeResolvedRow(file="b.py", line=2, recipe_id="y_rewrite", kind="rewrite"),
    ]

    merged = a.merge(b)
    # Whichever side wins, the merge MUST NOT have concatenated them.
    # Sanity: total length stays <= 1 (the result is at most one side's
    # rows, never both summed). The current implementation leaves the
    # merge target's list untouched, so we expect a's row to survive.
    assert len(merged.recipe_resolved) <= 1, (
        "Assessment.merge() must NOT concatenate recipe_resolved. "
        "Recipe data is assigned post-merge by render_assessment."
    )


def test_merge_signature_has_no_recipe_resolved_concat_in_source() -> None:
    """Source-level guarantee: Assessment.merge MUST NOT mention
    recipe_resolved in any way (no concat, no copy, no read). This catches
    a class of bugs that pure-behavioural assertions would miss."""
    import assess_ir
    merge_src = inspect.getsource(Assessment.merge)
    assert "recipe_resolved" not in merge_src, (
        "Assessment.merge must NOT touch recipe_resolved — the panel is "
        "post-merge assignment only (Tier-B Recipe-Data Isolation "
        "Guarantee). Source contains:\n" + merge_src
    )


# ---------------------------------------------------------------------------
# _load_recipe_edits guardrails
# ---------------------------------------------------------------------------


def test_load_recipe_edits_handles_missing_file(tmp_path: Path) -> None:
    assert _load_recipe_edits(tmp_path / "nonexistent.json") is None
    assert _load_recipe_edits(None) is None


def test_load_recipe_edits_handles_missing_key(tmp_path: Path) -> None:
    p = tmp_path / "state.json"
    p.write_text(json.dumps({"phase": 1}))
    assert _load_recipe_edits(p) == {}


def test_load_recipe_edits_handles_wrong_type(tmp_path: Path) -> None:
    p = tmp_path / "state.json"
    p.write_text(json.dumps({"recipe_edits": ["not", "a", "dict"]}))
    assert _load_recipe_edits(p) == {}


def test_load_recipe_edits_handles_corrupt_json(tmp_path: Path) -> None:
    p = tmp_path / "state.json"
    p.write_text("not valid json {")
    assert _load_recipe_edits(p) is None
